# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 17:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-date_added',)},
        ),
    ]
